name: Build

on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - run: ./gradlew --stacktrace check
